# Ideas.yml
# https://docs.github.com/ko/discussions/managing-discussions-for-your-community/syntax-for-discussion-category-forms
# https://docs.github.com/ko/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

title: "[Ideas] "